### ISSUE TITLE
missing sparkfun scraping script

### ISSUE THREAD

**Issue by ybakos** [osu-cascades/iot-lab-inventory#15]
@plark42 Where is the scraping script? Right now there is no way to bootstrap a devenv.

**Comment by plark42** [comment]
uploaded the scraper script(s):
1) scrape_data.py populates db, downloads images and files
2) update_db_category.py uses sparkfun's SKU code to select each part's category.

**Comment by ybakos** [comment]
Ok, I'll test them out and see if I can rebuild the db from scratch.
Once that works, we'll want to start using migrations.
