### ISSUE TITLE
missing images in static

### ISSUE THREAD

**Issue by ybakos** [osu-cascades/iot-lab-inventory#16]
Where are the parts images? _static_ has no image files in the repo.

**Comment by plark42** [comment]
i have them in my local repos (pdfs too).  I can share via google drive or USB stick.

**Comment by ybakos** [comment]
Sounds good - just share on gdrive w/ bakosy@oregonstate.edu

**Comment by ybakos** [comment]
Need to store these assets on gdrive / s3.
