### ISSUE TITLE
Replace Cart class with Cart Model

### ISSUE THREAD

**Issue by plark42** [osu-cascades/iot-lab-inventory#25]
Having Cart as a class is becoming problematic.. Cart model should hold one Order model object..

**Comment by ybakos** [comment]
Are you sure? Let me know where in the codebase you're seeing the friction.

**Comment by plark42** [comment]
when validating the cart quantities when the user clicks "Create Order".. 

- we can make it work with Cart class, but it's a bit ugly..

**Comment by plark42** [comment]
I made it work with a Cart class.  Not pretty, but ok for now.  can always refactor..
