### ISSUE TITLE
swap oauth for google login

### ISSUE THREAD

**Issue by ybakos** [osu-cascades/iot-lab-inventory#3]
The _flask_googlelogin_ package has been deprecated. See https://github.com/insynchq/flask-googlelogin

**Comment by ybakos** [comment]
@plark42 I've done some digging into this. A solid candidate is _requests-oauthlib_.

https://github.com/requests/requests-oauthlib
https://requests-oauthlib.readthedocs.io/en/latest/
http://bitwiser.in/2015/09/09/add-google-login-in-flask.html

I've created an [oauth2 branch](https://github.com/osu-cascades/iot-lab-inventory/tree/oauth2) that has a bunch of cleanup and also removes all the googlelogin stuff, ready to get things to work with _requests-oauthlib_.

**Comment by plark42** [comment]
Why not use a flask extension? e.g., flask-oauthlib ?  https://flask-oauthlib.readthedocs.io/en/latest/

**Comment by ybakos** [comment]
Whichever 😄
