### ISSUE TITLE
Add User roles

### ISSUE THREAD

**Issue by ybakos** [osu-cascades/iot-lab-inventory#4]

**Comment by plark42** [comment]
- should we add a "Role" model and a foreign key in each User? 

- or should we keep it simple and add a "role" string field in the User model?

**Comment by plark42** [comment]
@ybakos - what's the best order of operations for modifying the database schema?  

- say I want to add an "is_admin" boolean field to the User model.. how do I make use of flask-migrate to handle these changes?

**Comment by ybakos** [comment]
I believe you just make the change to the model and run `flask db migrate` and `flask db upgrade`.
https://flask-migrate.readthedocs.io/en/latest/

**Comment by plark42** [comment]
That's what I thought.. thanks!!

**Comment by plark42** [comment]
Now only admin can modify parts (create, edit, delete) and manage users.
